parameters:
  pool: {}
  terraformVersion: ""


stages:
- stage: ProvisionLZ
  displayName: "ProvisionLZ"
  jobs:
  - template: /.pipelines/02_jobs/lz_base.yml
    parameters:
      condition: |
        and
        (
          ne(canceled(), true),
          ne(failed(), true),
          eq(variables.base, 'yes'),
          ne(variables.terraformDestroy, 'yes')
        )
      dependsOn: ""
      pool:
        vmImage: Ubuntu 18.04
      terraformBackendContainerName: $(TERRAFORM_BACKEND_CONTAINER_NAME)
      terraformBackendStorageName: $(TERRAFORM_BACKEND_STORAGE_NAME)
      terraformVersion: ${{ parameters.terraformVersion }}
      vaultName: $(VAULT_NAME)
      svcConnection: $(SVC_CONNECTION)

  - template: /.pipelines/02_jobs/pester_infra.yml
    parameters:
      condition: |
        and
        (
          ne(canceled(), true),
          ne(failed(), true),
          eq(variables.pester, 'yes'),
          ne(variables.terraformDestroy, 'yes'),
          in(dependencies.LZ_Base.result, 'Succeeded', 'Skipped')
        )
      dependsOn: LZ_Base
      pool:
        name: myPool
      vaultName: $(VAULT_NAME)
      svcConnection: $(SVC_CONNECTION)