parameters:
- name: base
  displayName: "Base"
  type: boolean
  default: true

- name: pester
  displayName: "Pester"
  type: boolean
  default: true

- name: planDeploy
  displayName: "Plan Only"
  type: boolean
  default: true

name: "$(BuildID) $(Date:yyyy-MM-dd HH-mm) UTC ~ "

pr: none
trigger: none
variables:
- template: /.pipelines/config/sub-b31e023c78b8.config.yml
- template: /.pipelines/config/global.config.yml
- ${{ if eq(parameters.base, true) }}:
  - name: base
    value: yes
- ${{ if eq(parameters.pester, true) }}:
  - name: pester
    value: yes
- ${{ if eq(parameters.planDeploy, true) }}:
  - name: planDeploy
    value: yes

stages:
- template: /.pipelines/01_stage/lz_deploy.yml
  parameters:
    pool: ${{ variables.SVC_CONNECTION }}
    terraformVersion: $(TERRAFORM_VERSION)