parameters:
  condition: ""
  dependsOn: ""
  pesterList: ""
  pool: {}
  vaultName: ""
  svcConnection: ""

jobs:
- job: Pester_Infra
  condition: ${{ parameters.condition }}
  continueOnError: false
  dependsOn: ${{ parameters.dependsOn }}
  displayName: "Pester Infra"
  pool: ${{ parameters.pool }}
  workspace:
    clean: all
  steps:
  - checkout: self

  - template: /.pipelines/03_steps/az_vault.yml
    parameters:
      vaultName: ${{ parameters.vaultName }}
      svcConnection: ${{ parameters.svcConnection }}

  - task: PowerShell@2
    displayName: "Invoke Pester"
    env:
      ARMCLIENTSECRET: $(ARMCLIENTSECRET)
      TERRAFORMBACKENDACCESSKEY: $(TERRAFORMBACKENDACCESSKEY)
    inputs:
      arguments: >-
        -clientId "$(ARMCLIENTID)"
        -environment "$(TERRAFORM_ENVIRONMENT)"
        -list "${{ parameters.pesterList }}"
        -location "$(TERRAFORM_LOCATION)"
        -storageAccount "$(TERRAFORM_BACKEND_STORAGE_NAME)"
        -subscriptionName "$(ENVIRONMENT_NAME)"
        -tenantId "$(ARMTENANTID)"
      filePath: $(System.DefaultWorkingDirectory)/scripts/pester/tfstate-check/invoke-pester.ps1
      pwsh: true
      targetType: filePath
      workingDirectory: $(System.DefaultWorkingDirectory)/scripts/pester/tfstate-check/

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pester Artifact'
    inputs:
      targetPath: $(System.DefaultWorkingDirectory)/scripts/pester/tfstate-check/Infra-Pester-$(ENVIRONMENT_NAME).XML
      artifact: pester_infra_$(ENVIRONMENT_NAME)

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: $(System.DefaultWorkingDirectory)/scripts/pester/tfstate-check/Infra-Pester-$(ENVIRONMENT_NAME).XML
      testRunTitle: $(ENVIRONMENT_NAME)
      publishRunAttachments: true
    displayName: "Publish Results"